
// This file was generated by set-env.js. Do not modify manually.
// Angular's environment file generated from .env
export const environment = {
  production: false,
  // Add all variables from .env here
  CAPATCHA_SITE_KEY: '6Lf-UOsrAAAAAC44Yt-kaQJJO113yclaA86wHBEs'
};
